/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.my.project.drools_detector;
import org.junit.jupiter.api.Test;
//import com.my.project.drools_detector;


class Drools_detectorTest {
    @Test void appHasAGreeting() {
        //Drools_Detector classUnderTest = new Drools_Detector();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
