package com.my.project.drools_detector;

global java.util.List list

rule "Hello World"
    when
        m: Drools_detector.Message(status == Drools_detector.Message.HELLO, message: message)
    then
        System.out.println("r1, t");
        System.out.println(message);
        modify(m) { setMessage("Goodbye cruel world"), setStatus(Drools_detector.Message.GOODBYE)};
end

rule "Good Bye"
    dialect 'java'
    when
        Drools_detector.Message(status == Drools_detector.Message.GOODBYE, message: message)
    then
        System.out.println("r2, t");
        System.out.println(message);
end

