package com.my.project.drools_detector

import com.my.project.drools_detector.Drools_detector.Message;

global java.util.List list

rule "Hello World"
    when
        m: Message(status == Message.HELLO, message: message)
    then
        System.out.println("r1, t");
        System.out.println(message);
        modify(m) { setMessage("Goodbye cruel world"), setStatus(Message.GOODBYE)};
end

rule "Good Bye"
    dialect 'java'
    when
        Message(status == Message.GOODBYE, message: message)
    then
        System.out.println("r2, t");
        System.out.println(message);
end

